DataDictionary/Controllers/HomeController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web.Mvc;
using BannerDataDictionary.Models;
using Dapper;

namespace BannerDataDictionary.Controllers
{
    public class HomeController : ApplicationController
    {
        public static string BannerMessage = "<h4>Access to the Banner meta-data is limited to those individuals with existing individual, personal, non-departmental/non-application third-party* accounts or to those individuals whom have specifically requested Banner meta-data access via e-mail to: <a href=\"mailto:banner-sa@ucdavis.edu?subject=Banner Meta-Data Schema Access Request&body=Please setup the following UC Davis Login, i.e. Kerberos, IDs to the named profiles and associate user to profiles for the individuals listed below.  This is solely for the purpose of allowing access to the Banner Schema meta-data by way of the CAES Data Dictionary application.  No other Banner access is requested, intended or implied.  Thank you.  I have included the College, unit name, user\'s full name, title, kerberos ID, e-mail address and phone number, as well as supervisor\'s full name, title, e-mail address, phone number, plus the business purpose.\">banner-sa@ucdavis.edu</a>.</h4>" +
             "<br /><p>*Note: A Banner third-party account is a Banner database access account created for someone or something outside of the Banner team.&nbsp;&nbsp;An individual, personal account may have been requested by a single application developer in another unit, and would have been tied directly to that individual\'s UCD Login/Kerberos Id.&nbsp;&nbsp;Third-party <i>application</i> or <i>departmental</i> accounts are different because they are typically created for use by an application and/or for direct database access by a group of developers in a particular unit; therefore, the system has no way of knowing of which individual developers may be using the account, and must specifically request Banner meta-data access as outlined above.</p>";
                                    
        public ActionResult Index()
        {
            ViewBag.Message = "Oracle Linked Servers";
            using (var conn = new SqlConnection(ConfigurationManager.ConnectionStrings["MainDb"].ConnectionString))
            {
                conn.Open();
      
                var loginId = User.Identity.Name;
                var bannerUserList = conn.Query(string.Format("SELECT LoginId FROM BannerLoginIds WHERE LoginId = '{0}'", loginId)).ToList();
                var includeBannerItems = bannerUserList.Count() == 1 ? true : false;
                var resultList =
                    conn.Query<LinkedServer>(
                        string.Format("EXEC usp_GetOracleLinkedServerNames @IncludeBannerItems = {0}",
                                      includeBannerItems)).ToList();

                if (!includeBannerItems)
                    TempData["Message"] = BannerMessage;
            
                 return View(resultList);
            }
        }

        [AllowAnonymous]
        public ActionResult About()
        {
            ViewBag.Message = "About";
            return View();
        }

        [AllowAnonymous]
        public ActionResult Contact()
        {
            ViewBag.Message = "Contact";
            return View();
        }
    }
}

DataDictionary/Controllers/OwnersController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BannerDataDictionary.Models;
using Dapper;

namespace BannerDataDictionary.Controllers
{
    public class OwnersController : ApplicationController
    {
        public ActionResult Index(LinkedServer id)
        {
            if (id == null)
            {
                ViewBag.Message = "Error: Must provide a Linked Server and Database Owner";
                return RedirectToAction("Index", "Home", new {Message = "Must Select a Linked Server to continue!"});
            }
            else
            {
                var includeEmptyTables = id.IncludeEmptyTables ?? false;
                var linkedServerName = id.Name as string ?? "SIS";

                ViewBag.Message = linkedServerName + " Database Owners";

                using (var conn = new SqlConnection(ConfigurationManager.ConnectionStrings["MainDb"].ConnectionString))
                {
                    conn.Open();

                    var loginId = User.Identity.Name;
                    var bannerUserList = conn.Query(string.Format("SELECT LoginId FROM BannerLoginIds WHERE LoginId = '{0}'", loginId)).ToList();
                    var includeBannerItems = bannerUserList.Count() == 1 ? true : false;

                    var databaseOwners = conn.Query<DatabaseOwner>(
                            @"EXEC usp_GetLinkedServerDatabaseOwnersAndTableCount @LinkedServerNames = @linkedServerName, @IncludeEmptyTables = @includeEmptyTables, @IncludeBannerItems = @includeBannerItems",
                            new
                                {
                                    @linkedServerName = linkedServerName,
                                    @includeEmptyTables = includeEmptyTables,
                                    @includeBannerItems = includeBannerItems
                                }).ToList();
                   
                    return View(databaseOwners);
                }
            }
        }
    }
}

DataDictionary/Controllers/SearchController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using BannerDataDictionary.Models;
using Dapper;

namespace BannerDataDictionary.Controllers
{
    public class SearchController : ApplicationController
    {
        //
        // GET: /Search/

        public ActionResult Index()
        {
            var viewModel = new SearchModel();

            using (var conn = new SqlConnection(ConfigurationManager.ConnectionStrings["MainDb"].ConnectionString))
            {
                conn.Open();

                var loginId = User.Identity.Name;
                var bannerUserList = conn.Query(string.Format("SELECT LoginId FROM BannerLoginIds WHERE LoginId = '{0}'", loginId)).ToList();
                var includeBannerItems = bannerUserList.Count() == 1 ? true : false;

                viewModel.LinkedServers = conn.Query<LinkedServer>(string.Format("EXEC usp_GetOracleLinkedServerNames @IncludeBannerItems = {0}", includeBannerItems)).ToList();

                return View(viewModel);
            }
        }

        [HttpPost]
        public ActionResult Details(SearchModel model)
        {
            if (ModelState.IsValid)
            {
                using (var conn = new SqlConnection(ConfigurationManager.ConnectionStrings["MainDb"].ConnectionString))
                {
                    var searchString = model.SearchString;
                    var searchTables = model.SearchTables;
                    var searchColumns = model.SearchColumns;
                    var searchComments = model.SearchComments;
                    var selectedServerNames = model.SelectedServerNames;
                        //This what's populated when a user selects (a) linked server(s).
                    var selectedServerNamesString = "";
                    if (selectedServerNames != null && selectedServerNames.Any())
                    {
                        selectedServerNamesString = selectedServerNames.Aggregate(selectedServerNamesString,
                                                                                  (current, name) =>
                                                                                  current + (name + ","));
                        selectedServerNamesString = selectedServerNamesString.Substring(0,
                                                                                        selectedServerNamesString.Length -
                                                                                        1);
                    }

                    conn.Open();

                    var loginId = User.Identity.Name;
                    var bannerUserList = conn.Query(string.Format("SELECT LoginId FROM BannerLoginIds WHERE LoginId = '{0}'", loginId)).ToList();
                    var includeBannerItems = bannerUserList.Count() == 1 ? true : false;

                    var results =
                        conn.Query<SearchResult>(
                            @"SELECT * FROM dbo.udf_GetTableColumnCommentsResults(@searchString, @LinkedServerNames, 
                                @SearchTables, @SearchColumns, @SearchComments, @IncludeBannerItems)",
                            new {@searchString = searchString, @LinkedServerNames = selectedServerNamesString,
                                 @SearchTables = searchTables,
                                 @SearchColumns = searchColumns,
                                 @SearchComments = searchComments,
                                 @IncludeBannerItems = includeBannerItems 
                            }).ToList();

                    if (results.Count == 1)
                    {
                        // means we got back a single matching table => jump to table details page:
                        var result = results.FirstOrDefault();
                        return RedirectToAction("Details", "Tables", new Table { LinkedServerName = result.LinkedServerName, Owner = result.Owner, TableName = result.TableName });
                    }
                    return View(results);
                }
            }
            return View(model);
        }
    }
}

DataDictionary/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
    ViewBag.Message = "Oracle Data Dictionary";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    
    <h2>@ViewBag.Message</h2>
</hgroup>
<hr/>
<article style="font-size: medium;">
       
        <p>
            An application that collects miscellaneous table and column meta-data from various campus' Oracle databases and displays that information back out as an on-line data dictionary.
        </p>
        <p>
            Purpose: To provide a central location, i.e. URL, for viewing data dictionaries for all campus enterprise level databases.
        </p>
        <p class="text-error">
            Important Note: <i>No</i> actual data of any kind is displayed; only meta data describing the table schemas, etc.
        </p>

</article>


DataDictionary/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
    ViewBag.Message = "Computing Resources Unit (CRU)";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Application Support:</span>
        <span style="font-weight: bold;">Ken Taylor</span>
        <span>530-752-1288</span>
    </p>
    <p>
        <span class="label">Computing Support:</span>
        <span>530-754-7122</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Application Developer:</span>
        <span><a href="mailto:kentaylor@ucdavis.edu">KenTaylor@ucdavis.edu</a></span>
    </p>
    @*<p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>*@
    <p>
        <span class="label">Computing Support:</span>
        <span><a href="https://caeshelp.ucdavis.edu/?appname=Data%20Dictionary">https://caeshelp.ucdavis.edu/?appname=Data%20Dictionary</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        One Shields Ave<br />
        38 Mrak Hall<br/>
        Davis, CA 95616
    </p>
</section>

DataDictionary/Views/Home/Index.cshtml
@using BannerDataDictionary.Models
@model IList<BannerDataDictionary.Models.LinkedServer>
           
@{
    ViewBag.Title = "Index";
}

@section subhead
{
    <h1>@ViewBag.Message</h1>

    <div>
        <p>A listing of Oracle Linked Servers</p>
    </div>
}

@section AdditionalScripts
{}
@*<div>
    <h4>Access to the Banner meta-data is limited to those individuals with existing individual, personal, non-departmental/non-application third-party* 
        accounts or to those individuals whom have specifically requested Banner meta-data access via e-mail to: 
        <a href="mailto:banner-sa@ucdavis.edu?subject=Banner Meta-Data Schema Access Request&body=Please setup the following UC Davis Login, i.e. Kerberos, IDs to the named profiles and associate user to profiles for the individuals listed below.  This is solely for the purpose of allowing access to the Banner Schema meta-data by way of the CAES Data Dictionary application.  No other Banner access is requested, intended or implied.  Thank you.  I have included the College, unit name, user's full name, title, kerberos ID, e-mail address and phone number, as well as supervisor's full name, title, e-mail address, phone number, plus the business purpose.">banner-sa@ucdavis.edu</a>.</h4>
    <p>*Note: A Banner third-party account is a Banner database access account created for someone or something outside 
        of the Banner team.&nbsp;&nbsp;An individual, personal account may have been requested by a single application developer in another unit, 
        and would have been tied directly to that individual's UCD Login/Kerberos Id.&nbsp;&nbsp;Third-party <i>application</i> or <i>departmental</i> 
        accounts are different because they are typically created for use by an application and/or for direct database access by a group of developers
        in a particular unit; therefore, the system has no way of knowing of which individual developers may be using the account, 
        and must specifically request Banner meta-data access as outlined above.</p>
</div>*@
<div>
    <h3>Select a Linked Server to display a list of database owners (i.e., Schemas)</h3>
    <p>
    </p>

    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>Server Name</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.ActionLink(item.Name, "Index", "Owners", new LinkedServer { Name = item.Name }, null)</td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div>
    <h3>Search All Linked Servers for specific keywords or text</h3>
    <p>
        @Html.ActionLink("Global Search Page", "Index", "Search", null, null)
    </p>
</div>